message("2. Gather repeated cross-sections...")

# This script harmonizes and merges three cross-sectional waves of the RCVS (2018, 2021, and 2024). 
# The raw data for each wave are identical to those hosted in the RCVS repositories (Dataverse, Zenodo, and ICPSR).
# Due to modifications in the survey instrument (refer to the preprint for further details), 
# some variables were excluded from the unified dataset for the following reasons:

#a) the question was removed from the questionnaire;
#b) the question was not included in every wave;
#c) certain derived variables (with prefixes -resp, -victim, -offender) are no longer generated by default.

# However, we have retained several high-demand variables in the merged dataset even if they are not present in all waves. 
# These include nominal household income (Q571, added in 2021), detailed cybercrime data (Q662, Q663, added in 2021), 
# fear of crime indicators (Q81, Q82, Q83, added in 2021), and select others.

# Over time, some questions gained additional response options. 
# To ensure data consistency across the unified dataset, we have simplified (aggregated) certain responses.
# While we have aimed for the most comprehensive integration of the RCVS waves possible, t
# he raw data remain available for any user to re-assemble according to their specific research objectives.

# Add year of the wave
rcvs18[, year := 2018]
rcvs21[, year := 2021] 
rcvs24[, year := 2024] 

## Selecting variables' names from all df's for the future manual unification
# var_names18 <- as.data.frame(names(rcvs18))
# var_names21 <- as.data.frame(names(rcvs21))
# var_names24 <- as.data.frame(names(rcvs24))
# var_names24 <- rbind(var_names24, '', '')
# all_var_names <- cbind(var_names18, var_names21, var_names24)
# write.csv2(all_var_names, "./intermediate_files/all_var_names.csv",row.names = F)

# Settlement type----
# Fix some inconsistency
rcvs18[Q1005 == "МОСКВА", resp_place_population := 12506468]
rcvs18[Q1005 == "Санкт-Петербург", resp_place_population := 5351935]

# Add Q2003 (Tip_NP) to rcvs18
rcvs18[, Q2003 := fcase(
  resp_place_population >= 1e6, "города 1 млн и более",
  resp_place_population >= 250000 & resp_place_population < 1e6, "города от 250 тыс. до 1 млн",
  resp_place_population >= 50000 & resp_place_population < 250000, "города от 50 до 250 тыс.",
  resp_place_population >= 1000 & resp_place_population < 50000, "города менее 50 тыс., ПГТ",
  resp_place_population < 1000,  "сельский населенный пункт",
  default = "нет данных" 
)]

# Rename levels of Q2003 in rcvs24 and rcvs21
rcvs21[Q1005 == "Город федерального значения Москва", Q2003 := "города 1 млн и более"]
rcvs21[Q1005 == "Город федерального значения Санкт-Петербург", Q2003 := "города 1 млн и более"]
rcvs21[Q1005 == "Город федерального значения Севастополь", Q2003 := "города от 250 тыс. до 1 млн"]
rcvs21[Q2003 == "Москва", Q2003 := "города 1 млн и более"]

rcvs24[Q2003 == "город более 1 млн", Q2003 := "города 1 млн и более"]
rcvs24[Q2003 == "город от 500 тыс до 1 млн", Q2003 := "города от 250 тыс. до 1 млн"]
rcvs24[Q2003 == "город от 250 до 500 тыс", Q2003 := "города от 250 тыс. до 1 млн"]
rcvs24[Q2003 == "город от 100 до 250 тыс", Q2003 := "города от 50 до 250 тыс."]
rcvs24[Q2003 == "город от 50 до 100 тыс", Q2003 := "города от 50 до 250 тыс."]
rcvs24[Q2003 == "город менее 50 тыс", Q2003 := "города менее 50 тыс., ПГТ"]
rcvs24[Q2003 == "пгт", Q2003 := "города менее 50 тыс., ПГТ"]
rcvs24[Q2003 == "село", Q2003 := "сельский населенный пункт"]

rcvs24[Q1005 == "г. Москва", Q2003 := "города 1 млн и более"]
rcvs24[Q1005 == "г. Санкт-Петербург", Q2003 := "города 1 млн и более"]
rcvs24[Q1005 == "г. Севастополь", Q2003 := "города от 250 тыс. до 1 млн"]

# Remote crime-----
# Adapt Q661 and Q662 from 21-24 to Q66 in 18
rcvs21[, Q66 := fcase(
  Q661 == "Да, через телефон" | Q662 == "Да, через интернет", "Да, через телефон или интернет",
  Q661 == "Нет, не через телефон" | Q662 == "Нет, не через интернет", "Нет, не через телефон или интернет",
  Q661 == "Затрудняюсь ответить" | Q662 == "Затрудняюсь ответить", "Затрудняюсь ответить",
  default = NA_character_
)]

rcvs24[, Q66 := fcase(
  Q661 == "Да, через телефонный звонок" | Q662 == "Да, через интернет", "Да, через телефон или интернет",
  Q661 == "Нет, не через телефонный звонок" | Q662 == "Нет, не через интернет", "Нет, не через телефон или интернет",
  Q661 == "Затрудняюсь ответить" | Q662 == "Затрудняюсь ответить", "Затрудняюсь ответить",
  default = NA_character_
)]

# Property damage or loss------
# Adapt questions about property damage/destroy/taken away from 18 to Q221 in 21-24
rcvs18[, Q221 := fcase(
  Q20_1 == "Они были уничтожены" | Q20_1 == "Они были повреждены" | Q20_2 == "Они были уничтожены" | Q20_2 == "Они были повреждены" | Q20_3 == "Они были уничтожены" | Q20_3 == "Они были повреждены" | Q20_4 == "Они были уничтожены" | Q20_4 == "Они были повреждены" | Q20_5 == "Они были уничтожены" | Q20_5 == "Они были повреждены" | Q20_6 == "Они были уничтожены" | Q20_6 == "Они были повреждены" | Q20_7 == "Они были уничтожены" | Q20_7 == "Они были повреждены" | Q20_8 == "Они были уничтожены" | Q20_8 == "Они были повреждены" | Q20_9 == "Они были уничтожены" | Q20_9 == "Они были повреждены", "Повреждено/уничтожено",
  Q67_1 == 1 | Q67_2 == 1 | Q67_3 == 1 | Q67_4 == 1 | Q67_5 == 1 | Q67_6 == 1 | Q67_7 == 1 | Q67_8 == 1 | Q67_9 == 1, "Имуществом завладел другой человек",
  Q20_999 == 1 | Q67_999 == 1, "Затрудняюсь ответить",
  default = NA_character_
)]

# Physical damage----
# Converting Q26 from wide format to the long format in 18
rcvs18[, Q26 := fcase(
  Q26_1 == 1, "Нет",
  Q26_2 == 1, "Да, синяки или ссадины",
  Q26_3 == 1, "Да, повреждения серьёзнее, чем синяки или ссадины",
  default = NA_character_ 
)]

## victim_damage_physical fix
rcvs18[, victim_damage_physical := Q26]

# Talked/seen offender-----
# Unify Q611 and Q6 in 24 to match questions in Q6 18-21
rcvs24[, Q6 := fcase(
  Q6 == "Да" | Q611 == "Да", "Да",
  Q6 == "Нет" | Q611 == "Нет", "Нет",
  Q6 == "Затрудняюсь ответить" | Q611 == "Затрудняюсь ответить", "Затрудняюсь ответить",
  default = NA_character_ 
)]

# Initiated criminal or administrative proceedings----
# Refactor Q46 from old versions to the new one (binary)
rcvs21[, Q46 := fcase(
  Q46 == "Уголовное дело", "Да",
  Q46 == "Административное дело", "Да",
  Q46 == "Не было возбуждено ни уголовного, ни административного дела", "Нет",
  Q46 == "Затрудняюсь ответить / Не знаю / Не помню", "Затрудняюсь ответить/Не помню",
  default = NA_character_ 
)]

rcvs18[, Q46 := fcase(
  Q46 == "Уголовное дело", "Да",
  Q46 == "Административное дело", "Да",
  Q46 == "Не было возбуждено ни уголовного, ни административного дела", "Нет",
  Q46 == "Затрудняюсь ответить / Не знаю / Не помню", "Затрудняюсь ответить/Не помню",
  default = NA_character_ 
)]

# Rename variable
setnames(rcvs18, "victim_is_self_accuse", "victim_is_self_accused")
setnames(rcvs24, old = "Q571", new = "Q_loan")
setnames(rcvs24, old = "Q570", new = "Q571")
setnames(rcvs24, old = "Q570_1N", new = "Q571_1N")

# Keep pairs of labels and values for future restoration
attr(rcvs24$year, "label") <- "Год"
attr(rcvs24$Q66, "label") <- "Можно ли сказать, что в Вашем случае преступление произошло через телефон / интернет (например, злоумышленники Вам звонили или писали с просьбой перевести им деньги) или к Вашему случаю это неприменимо?"
attr(rcvs24$Q6, "label") <- "В момент преступления вы разговаривали со злоумышленником?"
key_pairs_rdd <- data.table(variable = names(rcvs24), label = label(rcvs24))
fwrite(key_pairs_rdd, file = "data/supplementary_data/key_pairs_rdd.csv")

# Download manually done unification
all_variables <- fread("data/supplementary_data/all_var_names_fixed.csv")
# Collecting all common variables
vars_bind <- c(as.vector(all_variables[, common]), c("Q571", "Q571_1N", "Q661", "Q662", "Q111", "region_iso", "weight", "resp_mean_household_income", "Q47_5", "Q47_6"))
vars_bind18 <- vars_bind[!vars_bind %in% setdiff(vars_bind, names(rcvs18))]

# Selecting only common variables in each wave
rcvs18_selected <- rcvs18[, ..vars_bind18]
rcvs21_selected <- rcvs21[, ..vars_bind]
rcvs24_selected <- rcvs24[, ..vars_bind]

# Save classes of all variables
check_all_options21 <- suppressWarnings(rbindlist(lapply(rcvs21_selected, function(x) { 
  
  data.table(labels = levels(x),  type = class(x),  n = sum(!is.na(x), na.rm = T), unique_labels = uniqueN(x[!is.na(x)]))
  
}), id = "variable", fill = T))

vars_numeric <- unique(check_all_options21[type == "numeric", variable])
vars_char <- c("ID", "Q5_1T")
vars_factor <- setdiff(vars_bind, union(vars_numeric, vars_char))

# Binding all waves in one df-----
## Recoding all variables to character type
rcvs18_selected[, names(rcvs18_selected) := lapply(.SD, as.character)]
rcvs21_selected[, names(rcvs21_selected) := lapply(.SD, as.character)]
rcvs24_selected[, names(rcvs24_selected) := lapply(.SD, as.character)]

all_waves <- rbind(rcvs18_selected, rcvs21_selected, rcvs24_selected, fill = T)

## Hard to tell variants unification
all_waves[, c(vars_factor) := lapply(.SD, function(x) { ifelse(x %in% c("Затрудняюсь ответить / не помню", "Затрудняюсь ответить/Не помню", "Затрудняюсь ответить / не помню / не могу сказать", "Затрудняюсь ответить / не знаю", "Затрудняюсь ответить, отказ говорить", "Затрудняюсь,отказ от ответа", "Затрудняюсь ответить (НЕ ЗАЧИТЫВАТЬ)"), "Затрудняюсь ответить", x) }), .SDcols = vars_factor]

# Fix variable levels-----
## income
all_waves[Q571 == "Сумма (руб.)", Q571 := "Да"]
all_waves[Q571 == "Отказ от ответа", Q571 := "Нет"]
all_waves[Q571 == "ЗАТРУДНЯЮСЬ ОТВЕТИТЬ", Q571 := "Затрудняюсь ответить"]

## via telephone
all_waves[, .N, by = Q661]
all_waves[Q661 == "Да, через телефон", Q661 := "Да, через телефонный звонок"]
all_waves[Q661 == "Нет, не через телефон", Q661 := "Нет, не через телефонный звонок"]

## Fix Q1005
all_waves[Q1005 == "Архангельская область без Ненецкого автономного округа", Q1005 := "Архангельская область"]
all_waves[Q1005 == "МОСКВА", Q1005 := "г. Москва"]
all_waves[Q1005 == "Город федерального значения Москва", Q1005 := "г. Москва"]
all_waves[Q1005 == "Санкт-Петербург", Q1005 := "г. Санкт-Петербург"]
all_waves[Q1005 == "Город федерального значения Санкт-Петербург", Q1005 := "г. Санкт-Петербург"]
all_waves[Q1005 == "Севастополь", Q1005 := "г. Севастополь"]
all_waves[Q1005 == "Город федерального значения Севастополь", Q1005 := "г. Севастополь"]
all_waves[Q1005 == "Республика Адыгея (Адыгея)", Q1005 := "Республика Адыгея"]
all_waves[Q1005 == "Республика Северная Осетия - Алания", Q1005 := "Республика Северная Осетия-Алания"]
all_waves[Q1005 == "Республика Татарстан (Татарстан)", Q1005 := "Республика Татарстан"]
all_waves[Q1005 == "Тюменская область без автономных округов", Q1005 := "Тюменская область"]
all_waves[Q1005 == "Чувашская Республика - Чувашия", Q1005 := "Чувашская Республика"]
all_waves[Q1005 == "Ханты-Мансийский автономный округ - Югра", Q1005 := "Ханты-Мансийский автономный округ-Югра"]
all_waves[Q1005 == "Заграница", Q1005 := "Другое"]
all_waves[Q1005 == "нет данных", Q1005 := "Нет данных"]

# Make other and non-response as one category
all_waves[is.na(Q1005) | Q1005 == "Другое", Q1005 := "Нет данных"]
# Harmonized with ISO coding
all_waves[Q1005 == "Нет данных", region_iso := NA_character_]

## Fix Q14
all_waves[Q14 == "В закрытом учреждении (армия, закрытое училище, больница, исправительная колония и т.п.)", Q14 := "В закрытом учреждении (армия, больница, ИК и т.д.)"]
all_waves[Q14 == "В подъезде, лифте или во дворе", Q14 := "В подъезде или во дворе"]
all_waves[Q14 == "На работе или на учёбе (школа, университет, детский сад, техникум)", Q14 := "На работе или на учебе (школа, университет, детский сад, техникум)"]
all_waves[Q14 == "На природе, в лесу, в парке", Q14 := "На природе, в лесу или парке"]
all_waves[Q14 == "В общественных зданиях (магазин, кафе, банк, поликлиника)", Q14 := "Общественные здания (магазины, кафе, банки, поликлиники)"]

all_waves[Q14 == "Затрудняюсь ответить", Q14 := NA_character_]
all_waves[Q14 == "Другое", Q14 := NA_character_]

## Fix Q15
all_waves[Q15 == "Тёмное", Q15 := "Темное"]

## Fix Q10
all_waves[Q10 == "Другое", Q10 := "Другой знакомый"]
all_waves[offender_is_familiar == 0, Q10 := "Незнакомец"]

## Fix Q68
all_waves[Q68 == "Дело ещё в процессе", Q68 := "Дело еще в процессе"]

## Fix Q49
all_waves[Q49 == "Дело ещё в процессе", Q49 := "Дело еще в процессе"]
all_waves[Q49 == "Нет, виновный не известен", Q49 := "Нет, виновный неизвестен"]

## Fix Q50
all_waves[Q50 == "Бандитами, криминальными авторитетами", Q50 := "Знакомые, близкие, друзья, частные лица (частные охранные структуры), бандиты, криминальные авторитеты"]
all_waves[Q50 == "Знакомые, близкие, друзья", Q50 := "Знакомые, близкие, друзья, частные лица (частные охранные структуры), бандиты, криминальные авторитеты"]
all_waves[Q50 == "Частные лица (частные охранные структуры)", Q50 := "Знакомые, близкие, друзья, частные лица (частные охранные структуры), бандиты, криминальные авторитеты"]

all_waves[Q50 == "Был известен или сам себя обнаружил", Q50 := "Затрудняюсь ответить / другое"]
all_waves[Q50 == "Другое", Q50 := "Затрудняюсь ответить / другое"]
all_waves[Q50 == "Не найден", Q50 := "Затрудняюсь ответить / другое"]
all_waves[Q50 == "Сдался", Q50 := "Затрудняюсь ответить / другое"]
all_waves[Q50 == "Затрудняюсь ответить", Q50 := "Затрудняюсь ответить / другое"]

## Fix Q51
all_waves[Q51 == "Дело ещё в процессе", Q51 := "Дело еще в процессе"]

## Fix Q53
all_waves[Q53 == "Не добивался / пока еще не добивался", Q53 := "Не добивался"]

## Fix Q69
all_waves[Q69 == "Другое", Q69 := "Затрудняюсь ответить"]

## Fix Q81
all_waves[Q81 == "Скорее небезопасно", Q81 := "Скорее не безопасно"]

## Fix Q572
all_waves[Q572 == "1 — полностью НЕ удовлетворен", Q572 := "1"]
all_waves[Q572 == "10 — полностью удовлетворен", Q572 := "10"]

## Fix Q78
all_waves[Q78 == "Да", Q78 := "Один"]
all_waves[Q78 == "Нет", Q78 := "С кем-то"]

## Fix Q80
all_waves[Q80 == "Размер домохозяйства (число)", Q80 := "Размер домохозяйства"]

## Fix Q61
all_waves[Q61 == "Неполное / незаконченное высшее образование (не меньше 3-х лет обучения в вузе)", Q61 := "Неполное/незаконченное высшее образование (не менее 3-х лет обучения в ВУЗе)"]
all_waves[Q61 == "Начальное", Q61 := "Начальное или неполное среднее"]
all_waves[Q61 == "Неполное среднее", Q61 := "Начальное или неполное среднее"]

## Fix Q64
all_waves[Q64 == "Сам работал, или сам работаю, или есть среди знакомых", Q64 := "Сам работал(-ю) или есть среди знакомых"]

## Fix crime_type
all_waves[crime_type == "Удаленное мошенничество", crime_type := "Удаленное преступление"]
all_waves[crime_type == "Угрозы", crime_type := "Прочее"]

## Fix crime_place
all_waves[crime_place == "В закрытом учреждении (армия, закрытое училище, больница, исправительная колония и т.п.)", crime_place := "В закрытом учреждении (армия, больница, ИК и т.д.)"]
all_waves[crime_place == "В подъезде, лифте или во дворе", crime_place := "В подъезде или во дворе"]
all_waves[crime_place == "На работе или на учёбе (школа, университет, детский сад, техникум)", crime_place := "На работе или на учебе (школа, университет, детский сад, техникум)"]
all_waves[crime_place == "На природе, в лесу, в парке", crime_place := "На природе, в лесу или парке"]
all_waves[crime_place == "В общественных зданиях (магазин, кафе, банк, поликлиника)", crime_place := "Общественные здания (магазины, кафе, банки, поликлиники)"]

all_waves[crime_place == "Затрудняюсь ответить", crime_place := NA_character_]
all_waves[crime_place == "Другое", crime_place := NA_character_]

## Fix crime_place_grouped
all_waves[crime_place_grouped == "В подъезде, лифте или во дворе", crime_place_grouped := "В подъезде или во дворе"]
all_waves[crime_place_grouped == "В общественных зданиях (магазин, кафе, банк, поликлиника)", crime_place_grouped := "Общественные здания (магазины, кафе, банки, поликлиники)"]

all_waves[crime_place_grouped == "Затрудняюсь ответить", crime_place_grouped := NA_character_]

## Fix victim_who_found_offender
all_waves[victim_who_found_offender == "Бандитами, криминальными авторитетами", victim_who_found_offender := "Знакомые, близкие, друзья, частные лица (частные охранные структуры), бандиты, криминальные авторитеты"]
all_waves[victim_who_found_offender == "Знакомые, близкие, друзья", victim_who_found_offender := "Знакомые, близкие, друзья, частные лица (частные охранные структуры), бандиты, криминальные авторитеты"]
all_waves[victim_who_found_offender == "Частные лица (частные охранные структуры)", victim_who_found_offender := "Знакомые, близкие, друзья, частные лица (частные охранные структуры), бандиты, криминальные авторитеты"]

all_waves[victim_who_found_offender == "Был известен или сам себя обнаружил", victim_who_found_offender := "Затрудняюсь ответить / другое"]
all_waves[victim_who_found_offender == "Другое", victim_who_found_offender := "Затрудняюсь ответить / другое"]
all_waves[victim_who_found_offender == "Не найден", victim_who_found_offender := "Затрудняюсь ответить / другое"]
all_waves[victim_who_found_offender == "Сдался", victim_who_found_offender := "Затрудняюсь ответить / другое"]
all_waves[victim_who_found_offender == "Затрудняюсь ответить", victim_who_found_offender := "Затрудняюсь ответить / другое"]

## Fix victim_compensation
all_waves[victim_compensation == "Не добивался / пока еще не добивался", victim_compensation := "Не добивался"]

## Recoding all variables to the original type
all_waves[, (vars_numeric) := lapply(.SD, as.numeric), .SDcols = vars_numeric]
all_waves[, (vars_factor) := lapply(.SD, as.factor), .SDcols = vars_factor]

# Set orders of factor variables-----
## Set orders of yes/no/hard to tell variables
cols_yes_no <- c("Q571", "Q75", "Q76", "Q18", "Q17", "Q22", "Q23", "Q24", "Q30", "Q27", "Q28", "Q29", "Q31", "Q33", "Q34", "Q32", "Q6", "Q9", "Q11", "Q13", "Q39", "Q40", "Q46", "Q52", "Q54", "Q58", "Q69", "Q70", "Q71", "Q72", "Q73", "Q65")
all_waves[, c(cols_yes_no) := lapply(.SD, function(x) { factor(x, levels = c("Да", "Нет", "Затрудняюсь ответить")) }), .SDcols = cols_yes_no]

## Q26
all_waves[, Q26 := factor(Q26, levels = c("Нет", "Да, синяки или ссадины", "Да, повреждения серьёзнее, чем синяки или ссадины"))]

## Q661
all_waves[, Q661 := factor(Q661, levels = c("Да, через телефонный звонок", "Нет, не через телефонный звонок", "Затрудняюсь ответить"))]

## 662
all_waves[, Q662 := factor(Q662, levels = c("Да, через интернет", "Нет, не через интернет", "Затрудняюсь ответить"))]

## Q2001
all_waves[, Q2001 := factor(Q2001, levels = c("Центральный ФО", "Северо-Западный ФО","Приволжский ФО", "Южный ФО", "Северо-Кавказский ФО", "Уральский ФО","Сибирский ФО", "Дальневосточный ФО", "Не определён"))]

## Q2003
all_waves[, Q2003 := factor(Q2003, levels = c("города 1 млн и более", "города от 250 тыс. до 1 млн", "города от 50 до 250 тыс.", "города менее 50 тыс., ПГТ", "сельский населенный пункт", "нет данных"))]

## Q66
all_waves[, Q66 := factor(Q66, levels = c("Да, через телефон или интернет", "Нет, не через телефон или интернет", "Затрудняюсь ответить"))]

## Q15
all_waves[, Q15 := factor(Q15, levels = c("Светлое", "Темное", "Затрудняюсь ответить"))]

## Q16
all_waves[, Q16 := factor(Q16, levels = c("Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь", "Затрудняюсь ответить"))]

## Q77
all_waves[, Q77 := factor(Q77, levels = c("Зима", "Весна", "Лето", "Осень", "Затрудняюсь ответить"))]

## Q221
all_waves[, Q221 := factor(Q221, levels = c("Повреждено/уничтожено", "Имуществом завладел другой человек", "Затрудняюсь ответить"))]

## Q7
all_waves[, Q7 := factor(Q7, levels = c("Один", "Несколько", "Затрудняюсь ответить"))]

# Q8
all_waves[, Q8 := factor(Q8, levels = c("Мужчина", "Женщина", "Затрудняюсь ответить"))]

## Q68
all_waves[, Q68 := factor(Q68, levels = c("Да", "Нет", "Дело еще в процессе", "Затрудняюсь ответить"))]

## Q49
all_waves[, Q49 := factor(Q49, levels = c("Да, виновный известен", "Нет, виновный неизвестен", "Дело еще в процессе", "Затрудняюсь ответить"))]

## Q51
all_waves[, Q51 := factor(Q51, levels = c("Да", "Нет", "Дело еще в процессе", "Затрудняюсь ответить"))]

## Q53
all_waves[, Q53 := factor(Q53, levels = c("Не добивался", 
                                          "Добивался, но ничего не удалось",
                                          "Добился частичной",
                                          "Добился полной компенсации",
                                          "Затрудняюсь ответить"))]

## Q57
all_waves[, Q57 := factor(Q57, levels = c("Едва сводим концы с концами, денег не хватает на продукты",
                                          "На продукты хватает, на одежду нет",
                                          "На продукты и одежду хватает, на технику и мебель нет",
                                          "На технику и мебель хватает, на большее денег нет",
                                          "Можем позволить автомобиль, но квартиру или дачу нет",
                                          "Можем позволить себе практически все: квартиру и т.д.",
                                          "Затрудняюсь ответить",
                                          "Отказ от ответа"))]

## Q78
all_waves[, Q78 := factor(Q78, levels = c("Один", "С кем-то", "Затрудняюсь ответить"))]

## Q79
all_waves[, Q79 := factor(Q79, levels = c("Да, официальный супруг(-а)", "Да, гражданский супруг(-а)", "Нет", "Затрудняюсь ответить"))]

## Q64
all_waves[, Q64 := factor(Q64, levels = c("Нет", "Сам работал(-ю) или есть среди знакомых", "Затрудняюсь ответить"))]

## victim_compensation
all_waves[, victim_compensation := factor(victim_compensation, levels = c("Не добивался", "Добивался, но ничего не удалось", "Добился частичной", "Добился полной компенсации", "Затрудняюсь ответить"))]

## Q61
all_waves[, Q61 := factor(Q61, levels = c("Начальное или неполное среднее", "Полное среднее", "Среднее специальное, среднее техническое или начальное профессиональное", "Неполное/незаконченное высшее образование (не менее 3-х лет обучения в ВУЗе)", "Высшее", "Затрудняюсь ответить"))]

## resp_edu
all_waves[, resp_edu := factor(resp_edu, levels = c("Полное среднее и ниже", "Среднее спец-ное/техническое или нач-ное профес-ное", "Высшее и незаконченное высшее"))]

## Fix Q47 due to filters present in 24 - deleting remote crimes for 18 & 21 in reporting
all_waves[year %in% c(2018, 2021) & crime_type %in% c("Удаленное преступление", "Покушение на удаленное преступление"), Q47_1 := NA_integer_]
all_waves[year %in% c(2018, 2021) & crime_type %in% c("Удаленное преступление", "Покушение на удаленное преступление"), Q47_2 := NA_integer_]
all_waves[year %in% c(2018, 2021) & crime_type %in% c("Удаленное преступление", "Покушение на удаленное преступление"), Q47_3 := NA_integer_]
all_waves[year %in% c(2018, 2021) & crime_type %in% c("Удаленное преступление", "Покушение на удаленное преступление"), Q47_4 := NA_integer_]
all_waves[year %in% c(2018, 2021) & crime_type %in% c("Удаленное преступление", "Покушение на удаленное преступление"), Q47_888 := NA_integer_]
all_waves[year %in% c(2018, 2021) & crime_type %in% c("Удаленное преступление", "Покушение на удаленное преступление"), Q47_999 := NA_integer_]


## Fix Q15 -- like Q47
all_waves[Q15 %in% c("Светлое", "Темное", "Затрудняюсь ответить") & year %in% c(2018, 2021) & crime_type %in% c("Удаленное преступление", "Покушение на удаленное преступление"), Q15 := NA_character_]

## Fix Q9-Q11 -- add filter Q8<3 for 18 & 21
all_waves[Q8 == "Затрудняюсь ответить" & year %in% c(2018, 2021), Q9 := NA_character_]
all_waves[Q8 == "Затрудняюсь ответить" & year %in% c(2018, 2021), Q10 := NA_character_]
all_waves[Q8 == "Затрудняюсь ответить" & year %in% c(2018, 2021), Q11 := NA_character_]

## Fix Q13 -- like Q47
all_waves[Q13 %in% c("Да", "Нет", "Затрудняюсь ответить") & year %in% c(2018, 2021) & crime_type %in% c("Удаленное преступление", "Покушение на удаленное преступление"), Q13 := NA_character_]

# Handle infinity result
all_waves[is.infinite(victim_damage_rub_lg), victim_damage_rub_lg := 0]

# Make proper order
setcolorder(all_waves, c("ID", "year"))

# Check results-----
# Compare all variable-value percentage
#all_waves_molten <- data.table::melt(all_waves, id.vars = c("ID", "year"), na.rm = F, value.factor = F)
#all_waves_molten <- all_waves_molten[!variable %in% c("IVDur", "Q5_1T", "Q75_1N", "Q76_1N", "Q2", "Q21_1N", "Q80_1N", "victim_damage_rub", "victim_damage_rub", "victim_damage_rub_lg")]
#all_waves_molten <- all_waves_molten[, .(n = .N), by = .(year, variable, value)]
#all_waves_molten[, percent := round(n/sum(n)*100, 1), by = .(year, variable)]
#all_waves_molten <- dcast(all_waves_molten, variable + value ~ year, value.var = "percent")